server:
  port: 9007
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    

spring:
  application:
    name: api-gateway 
  cloud:
    gateway:
      routes:
        - id: token-service
          uri: lb://token-service
          predicates:
            - Path=/get/**
        - id: tokenmanagement-service
          uri: lb://tokenmanagement-service
          predicates:
            - Path=/api/**    
        - id: communication-scaffold-service
          uri: lb://communication-scaffold-service
          predicates:
            - Path=/v1/**
          filters:
          - name: CircuitBreaker
            args:
              name: communication-scaffold-service
              fallbackuri: forward:/scaffoldServiceFallBack
        - id: feign-client-service
          uri: lb://feign-client-service
          predicates:
            - Path=/feignClient/**
          filters:
          - name: CircuitBreaker
            args:
              name: feign-client-service
              fallbackuri: forward:/feignServiceFallBack 
        - id: chatroom-service
          uri: lb://chatroom-service
          predicates:
            - Path=
          