server:
  port: 9007
  
eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway 
  cloud:
    gateway:
      routes:
        - id: token-service
          uri: lb://token-service
          predicates:
            - Path=/get/**
        - id: tokenmanagement-service
          uri: lb://tokenmanagement-service
          predicates:
            - Path=/api/**  
        - id: chatroom-service
          uri: lb://chatroom-service
          predicates:
            - Path=
          